apiVersion: v2
name: monitoring
description: A Helm chart for Prometheus and Grafana monitoring stack
type: application
version: 0.1.1
appVersion: "1.0.0"
keywords:
  - prometheus
  - grafana
  - monitoring
  - observability
maintainers:
  - name: DevOps Team

