{{- if .Values.mongodb.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "devops-challenge-app.mongodb.labels" . | nindent 4 }}
spec:
  type: {{ .Values.mongodb.service.type }}
  ports:
    - port: {{ .Values.mongodb.service.port }}
      targetPort: 27017
      protocol: TCP
      name: mongodb
  selector:
    {{- include "devops-challenge-app.mongodb.selectorLabels" . | nindent 4 }}
{{- end }}

