{{- if not .Values.mongodbSecret.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "devops-challenge-app.mongodb.secretName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "devops-challenge-app.mongodb.labels" . | nindent 4 }}
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: {{ .Values.mongodbSecret.username }}
  MONGO_INITDB_ROOT_PASSWORD: {{ .Values.mongodbSecret.password }}
  MONGO_INITDB_DATABASE: {{ .Values.mongodbSecret.database }}
{{- end }}

