name: Docker Image CI

on:
  push:
    branches: ["main", "develop"]
  pull_request:
    branches: ["main", "develop"]
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  # SAST: Static Application Security Testing
  njsscan:
    runs-on: ubuntu-latest
    name: njsscan code scanning
    steps:

    # Checkout the code
    - name: Checkout the code
      uses: actions/checkout@v4.2.2

    # Setup Python
    - uses: actions/setup-python@v5.3.0
      with:
        python-version: '3.12'

    # Code Static Analysis with njsscan
    - name: nodejsscan-scan
      id: njsscan
      uses: ajinabraham/njsscan-action@master
      with:
        args: '. --sarif --output sast-analysis.sarif || true'

    # Upload SARIF file as an Artifact to download and view
    - name: Upload SARIF as an Artifact
      uses: actions/upload-artifact@v4
      with:
        name: sast-analysis.sarif
        path: sast-analysis.sarif

  # Build Docker image
  build:
    name: Build Production Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v5
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build production Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./app
          file: ./app/Dockerfile
          target: production
          tags: tech-challenge-app:production
          push: false
          load: true
          platforms: linux/amd64
          build-args: |
            NODE_ENV=production

      - name: Run Trivy image scanner
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: 'tech-challenge-app:production'
          format: 'sarif'
          output: 'trivy-image.sarif'
          severity: 'CRITICAL,HIGH'
          #exit-code: '1' # Fail build on critical/high vulnerabilities

      # Upload SARIF file as an Artifact to download and view
      - name: Upload Trivy SARIF as an Artifact
        uses: actions/upload-artifact@v4
        with:
          name: trivy-image.sarif
          path: trivy-image.sarif

      # - name: Run Trivy with table format for image report
      #   uses: aquasecurity/trivy-action@master
      #   with:
      #     image-ref: 'tech-challenge-app:production'
      #     format: 'table'
      #     severity: 'CRITICAL,HIGH'
      #     exit-code: '1'
