{{- if and .Values.grafana.enabled .Values.grafana.storage.storageClass }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "monitoring.fullname" . }}-grafana-storage
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "monitoring.grafana.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.grafana.storage.storageClass }}
  resources:
    requests:
      storage: {{ .Values.grafana.storage.size }}
{{- end }}

