{{- if .Values.grafana.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "monitoring.fullname" . }}-grafana
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "monitoring.grafana.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: grafana
  selector:
    {{- include "monitoring.grafana.selectorLabels" . | nindent 4 }}
{{- end }}


